### ISSUE TITLE
UpdateNewChannelMessage

### ISSUE THREAD

**Issue by nijames** [Herklos/CryptoBot#1]
@Herklos please email me at nijames@g.clemson.edu

Got an error: 
C:\Users\*********\Desktop\CryptoBot-master>python main.py --backtest
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from telethon.tl.types import UpdateNewChannelMessage
ImportError: No module named 'telethon'

**Comment by Herklos** [comment]
Hi, you just have to install [this](https://pypi.python.org/pypi/Telethon/0.16.0.11) package by using the [pip](https://pypi.python.org/pypi/pip/) installer : 
`pip install telethon`
